export const EVENT_VENUES = [
  "Student Activity Centre",
  "Snackers",
  "IT Building - Lab 1",
  "Central Lawn",
  "Mega Ground",
  "MBH Ground",
  "OAT",
  "CSH",
  "VCH",
  "Science Block",
  "Community Center",
  "NITA Temple",
  "LT",
  "Online",
  "Department Building",
  "Others",
];